# Generated by Django 4.2.15 on 2025-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
