# Generated by Django 4.2.15 on 2025-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdata_order_id_orderstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
