# Generated by Django 4.2.15 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderdata_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Processing', max_length=50),
        ),
    ]
